server:
  port: 8082
  servlet:
    context-path: /api/auth

spring:
  application:
    name: ec-auth-srv
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true          # ğŸ‘‰ ÄÄƒng kÃ½ báº±ng IP thay vÃ¬ hostname
    hostname: localhost              # ğŸ‘‰ Ghi rÃµ Ä‘á»ƒ trÃ¡nh lá»—i DNS
    instance-id: ${spring.application.name}:${server.port}   # Dá»… phÃ¢n biá»‡t trong dashboard

application:
  security:
    jwt:
      secret-key: 8e29c681e354368d6ec0358461b9897180c6b9c9e77754cad6cd1c042e306b028e9e214b41e4632576f2e6f0899d4b165f5bb193199702f9c336cfffb0db5d19
      expiration: 86400000
      refresh-token:
        expiration: 604800000
