server:
  port: 8085
  servlet:
    context-path: /api/notifications

spring:
  application:
    name: ec-notification-srv
  datasource:
    url: jdbc:postgresql://localhost:5432/eContract_notification
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: pvt1213.phamvantu@gmail.com
    password: lizy ouxz rhyg hayg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true          # üëâ ƒêƒÉng k√Ω b·∫±ng IP thay v√¨ hostname
    hostname: localhost              # üëâ Ghi r√µ ƒë·ªÉ tr√°nh l·ªói DNS
    instance-id: ${spring.application.name}:${server.port}   # D·ªÖ ph√¢n bi·ªát trong dashboard

application:
  security:
    jwt:
      secret-key: 8e29c681e354368d6ec0358461b9897180c6b9c9e77754cad6cd1c042e306b028e9e214b41e4632576f2e6f0899d4b165f5bb193199702f9c336cfffb0db5d19
      expiration: 86400000
      refresh-token:
        expiration: 604800000